/*
 * Generated by Cougaar QoS FrameGen
 *   from c:\marla\mmon\cougaar\HEAD\qos\src\org\cougaar\core\qos\frame\topology\cougaar-topology-protos.xml
 *   at Mar 14, 2007 4:18:10 PM
 *
 * Copyright BBN Technologies 2006
 *
 */
package org.cougaar.core.qos.frame.topology;

import org.cougaar.core.qos.frame.DataFrame;
import org.cougaar.core.qos.frame.FrameSet;
import org.cougaar.core.util.UID;

public class IndicatorOnAgent
    extends Contains {
    /**
    * 
    */
   private static final long serialVersionUID = 1L;


   static {
        org.cougaar.core.qos.frame.FrameMaker __fm = 
            new org.cougaar.core.qos.frame.FrameMaker() {
                public DataFrame makeFrame(FrameSet frameSet, UID uid) {
                     return new IndicatorOnAgent(frameSet, uid);
                }
            };
            DataFrame.registerFrameMaker("org.cougaar.core.qos.frame.topology", "IndicatorOnAgent", __fm);
    }


    public IndicatorOnAgent(UID uid) {
        this(null, uid);
    }


    public IndicatorOnAgent(FrameSet frameSet,
                            UID uid) {
        super(frameSet, uid);
    }


    @Override
   public String getKind() {
        return "IndicatorOnAgent";
    }


    @Override
   public String getParentPrototype() {
        return "agent";
    }


    @Override
   public String getChildPrototype() {
        return "indicator";
    }


    @Override
   protected void collectSlotNames(java.util.Set<String> slots) {
        super.collectSlotNames(slots);
    }
}
