/*
 * Generated by Cougaar QoS FrameGen
 *   from /Volumes/Data/cougaar/HEAD/qos/src/org/cougaar/core/qos/frame/topology/cougaar-topology-protos.xml
 *   at Aug 1, 2006 3:59:45 PM
 *
 * Copyright BBN Technologies 2006
 *
 */
package org.cougaar.core.qos.frame.topology;

import org.cougaar.core.qos.frame.DataFrame;
import org.cougaar.core.qos.frame.FrameSet;
import org.cougaar.core.qos.frame.SlotDescription;
import org.cougaar.core.util.UID;

public class Thing
    extends DataFrame {
    static {
        org.cougaar.core.qos.frame.FrameMaker __fm = 
            new org.cougaar.core.qos.frame.FrameMaker() {
                public DataFrame makeFrame(FrameSet frameSet, UID uid) {
                     return new Thing(frameSet, uid);
                }
            };
            DataFrame.registerFrameMaker("org.cougaar.core.qos.frame.topology", "thing", __fm);
    }
    private String name;


    public Thing(UID uid) {
        this(null, uid);
    }


    public Thing(FrameSet frameSet,
                 UID uid) {
        super(frameSet, uid);
    }


    public String getKind() {
        return "thing";
    }


    protected void collectSlotValues(java.util.Properties __props) {
        super.collectSlotValues(__props);
        Object __value;
        __value = getName__AsObject();
        __props.put("name", __value != null ? __value : NIL);
    }


    public String getName() {
        return name;
    }


    String getName__NoWarn() {
        return name;
    }


    Object getName__AsObject() {
        return name;
    }


    protected void initializeName(String new_value) {
        this.name = new_value;
        slotInitialized("name", new_value);
    }


    void initializeName__AsObject(Object new_value) {
        this.name = force_String(new_value);
        slotInitialized("name", new_value);
    }
    private static final String name__SlotVar__ = "name".intern();


    protected Object getLocalValue(String __slot) {
       String __key = __slot.intern();
       if (name__SlotVar__ == __key)
            return getName__AsObject();
       else
           return null;
    }


    protected void setLocalValue(String __slot,
                                 Object __value) {
    }


    protected void initializeLocalValue(String __slot,
                                 Object __value) {
       String __key = __slot.intern();
       if (name__SlotVar__ == __key)
            initializeName__AsObject(__value);
    }


    protected void collectSlotNames(java.util.Set<String> slots) {
        super.collectSlotNames(slots);
        slots.add("name");
    }


    public SlotDescription slotMetaData__Name() {
        SlotDescription __desc = new SlotDescription();
        __desc.name = "name";
        __desc.prototype = "thing";
        __desc.is_writable = false;
        Object __value;
        __value = name;
        if (__value != null) {
            __desc.is_overridden = true;
            __desc.value = __value;
        } else {
            __desc.is_overridden = false;
        }
        return __desc;
    }


    protected void collectSlotDescriptions(java.util.Map<String,SlotDescription> map) {
        super.collectSlotDescriptions(map);
        map.put("name", slotMetaData__Name());
    }
}
