/*
 * Generated by Cougaar QoS FrameGen
 *   from /Volumes/Data/Projects/cougaar/HEAD/qos/src/org/cougaar/core/qos/frame/scale/test-scale-protos.xml
 *   at Aug 3, 2006 10:09:21 AM
 *
 * Copyright BBN Technologies 2006
 *
 */
package org.cougaar.core.qos.frame.scale;

import org.cougaar.core.qos.frame.DataFrame;
import org.cougaar.core.qos.frame.FrameSet;
import org.cougaar.core.util.UID;

public class Antilevel2OnAntilevel1
    extends Relationship {
    /**
    * 
    */
   private static final long serialVersionUID = 1L;


   static {
        org.cougaar.core.qos.frame.FrameMaker __fm = 
            new org.cougaar.core.qos.frame.FrameMaker() {
                public DataFrame makeFrame(FrameSet frameSet, UID uid) {
                     return new Antilevel2OnAntilevel1(frameSet, uid);
                }
            };
            DataFrame.registerFrameMaker("org.cougaar.core.qos.frame.scale", "antilevel2OnAntilevel1", __fm);
    }


    public Antilevel2OnAntilevel1(UID uid) {
        this(null, uid);
    }


    public Antilevel2OnAntilevel1(FrameSet frameSet,
                                  UID uid) {
        super(frameSet, uid);
    }


    @Override
   public String getKind() {
        return "antilevel2OnAntilevel1";
    }


    @Override
   public String getParentPrototype() {
        return "antilevel1";
    }


    @Override
   public String getChildPrototype() {
        return "antilevel2";
    }


    @Override
   protected void collectSlotNames(java.util.Set<String> slots) {
        super.collectSlotNames(slots);
    }
}
