#if !defined(COUGAAR_QOSKETS)
#define COUGAAR_QOSKETS

#include "gen/MT.idl"
#include "gen/MTInstrumented.idl"
#include "instrumentation/qdl/Instrumentation.idl"

module org {
    module cougaar {
	module core {
	    module service {
		interface LoggingService;
	    };
	};

        module lib {
            module quo {
                interface DiagnoseDelegateQosket : qosket::instrumentation::InstrumentationDelegateQosket {
                    void runDiagnostic (in org::cougaar::core::mts::Message m, in org::cougaar::core::mts::MT mt);
                };
                interface CompressQosket {
                    void setInstrumentedServer (in org::cougaar::lib::mquo::MTInstrumented object);
                    void setLoggingService (in org::cougaar::core::service::LoggingService log);
                };
                interface CompressDelegateQosket {
                    void runCompression (in org::cougaar::core::mts::Message message);
                    void runSerializeOnly (in org::cougaar::core::mts::Message message);
                    void runSerializeAndCompress (in org::cougaar::core::mts::Message message);
                };
                interface DiagnoseQosket : qosket::instrumentation::InstrumentationQosket {
                    void setLoggingService (in org::cougaar::core::service::LoggingService log);

                };
                interface LoggingQosket {
                    void setLoggingService (in org::cougaar::core::service::LoggingService log);
                };
            };
        };
    };
};
#endif
