#if !defined(COUGAAR_QOSKETS)
#define COUGAAR_QOSKETS

#include "MT.idl"
#include "MTInstrumented.idl"
#include "instrumentation/qdl/Instrumentation.idl"

module org {
    module cougaar {
        module lib {
            module quo {
                interface DiagnoseDelegateQosket : qosket::instrumentation::InstrumentationDelegateQosket {
                    void runDiagnostic (in org::cougaar::core::mts::Message m, in org::cougaar::core::mts::MT mt);
                };
                interface CompressQosket {
                    void setInstrumentedServer (in org::cougaar::lib::quo::MTInstrumented object);
                };
                interface CompressDelegateQosket {
                    void runCompression (in org::cougaar::core::mts::Message message);
                    void runSerializeOnly (in org::cougaar::core::mts::Message message);
                    void runSerializeAndCompress (in org::cougaar::core::mts::Message message);
                };
                interface DiagnoseQosket : qosket::instrumentation::InstrumentationQosket {
                };
                interface LoggingQosket {
                };
            };
        };
    };
};
#endif
