#if !defined(REMOTESSL_IDL)
#define REMOTESSL_IDL

#include "quo.idl"
#include "gen/MT.idl"
#include "gen/DestinationLink.idl"


module org {
    module cougaar {
	module core {
	    module qos {
		module monitor {
		    interface QosMonitorService;
		};
	    };
	};

	module lib {
	    module quo {
		interface TrafficMaskQosket {
		};

		interface RemoteSSLQosket {
		    void setDestinationLink(in org::cougaar::core::mts::DestinationLink link);
		    void setServices(in quo::ValueSC trust,
				     in quo::ValueSC useSSL);
		};

		interface RemoteSSLDelegateQosket {
		    long computeCost(in org::cougaar::core::mts::AttributedMessage msg);
		};
	    };
	};
    };
};

#endif
