/*
 * =====================================================================
 * (c) Copyright 2001  BBNT Solutions, LLC
 * =====================================================================
 */

// quo.idl,v

#if !defined(MT_IDL)
#define MT_IDL

module cougaar {

    typedef sequence<octet> bytes;

    exception CorbaMisdeliveredMessage {
    };


    interface MT {
	bytes rerouteMessage(in bytes message) 
	    raises(CorbaMisdeliveredMessage);
    };

};


#endif
