/* -*- JAVA -*- $Id: CompressDelegateQosket.java,v 1.4 2001-11-02 17:07:55 psharma Exp $ */

// ****** Code generated by the QuO codegenerator version 3.0.7 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface CompressDelegateQosket
{
  public void runCompression(org.cougaar.core.society.Message message);
  public void runSerializeOnly(org.cougaar.core.society.Message message);
  public void runSerializeAndCompress(org.cougaar.core.society.Message message);
}
