/* -*- JAVA -*- */

// ****** Code generated by the QuO codegenerator 3.0.9 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface CompressQosket
{
  public void setInstrumentedServer(org.cougaar.lib.mquo.MTInstrumented object);
  public void setLoggingService(org.cougaar.core.service.LoggingService log);
}
