/* -*- JAVA -*- */

// ****** Code generated by the QuO codegenerator 3.0.9 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface CompressDelegateQosket
{
  public void runCompression(org.cougaar.core.mts.Message message);
  public void runSerializeOnly(org.cougaar.core.mts.Message message);
  public void runSerializeAndCompress(org.cougaar.core.mts.Message message);
}
