/* -*- JAVA -*- */

// ****** Code generated by the QuO codegenerator 3.0.10 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface CompressDelegateQosket
{
  public org.cougaar.core.mts.MessageAttributes runCompression(org.cougaar.core.mts.AttributedMessage message);
  public org.cougaar.core.mts.MessageAttributes runSerializeOnly(org.cougaar.core.mts.AttributedMessage message);
  public org.cougaar.core.mts.MessageAttributes runSerializeAndCompress(org.cougaar.core.mts.AttributedMessage message);
}
