/* -*- JAVA -*- */

// ****** Code generated by the QuO codegenerator 3.0.10 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface DiagnoseDelegateQosket
       extends com.bbn.quo.qosket.instrumentation.InstrumentationDelegateQosket
{
  public org.cougaar.core.mts.MessageAttributes runDiagnostic(org.cougaar.core.mts.AttributedMessage m, org.cougaar.core.mts.MT mt);
}
