/* -*- JAVA -*- */

// ****** Code generated by the QuO codegenerator 3.0.10 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo ;

public class MTDiagnoseAdapter
       extends org.cougaar.lib.quo.MTDiagnoseDelegate_client
       implements org.cougaar.lib.quo.DiagnoseQosket 
{
  private org.cougaar.lib.mquo.DiagnoseQosketImpl qosket;

  // Constructor for BQAdapter
  public MTDiagnoseAdapter() 
  {
     this.qosket  = new org.cougaar.lib.mquo.DiagnoseQosketImpl();
     set_qosket (qosket);
  }


  public void initSysconds (com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
     qosket.initSysconds(kernel); 
  }

  public void initCallbacks ()
  {
     qosket.initCallbacks(); 
  }

  public void linkContract (com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
     set_contract_Diagnose( qosket.initContract ("Diagnose", kernel) );
  }

  public com.bbn.quo.rmi.Contract initContract(String name,
                           String interfaceName,
                           com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
     return qosket.initContract(name, interfaceName, kernel);
  }

  public void linkRemoteObject( org.cougaar.core.mts.MT remote_obj)
  {
     set_remoteObj ( remote_obj );
  }

  // Qosket methods from IDL
  // inherited methods and attributes of org.cougaar.lib.quo.DiagnoseQosket
  public void setInstrumentedServer(java.lang.Object server)
  {
     qosket.setInstrumentedServer ( server );
  }


  // local methods and attributes of org.cougaar.lib.quo.DiagnoseQosket
  public void setLoggingService(org.cougaar.core.service.LoggingService log)
  {
     qosket.setLoggingService ( log );
  }

}

