/* -*- JAVA -*- $Id: MTDiagnoseAdapter.java,v 1.1 2001-10-18 21:34:29 psharma Exp $ */

// ****** Code generated by the QuO codegenerator version 3.0.7 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo ;

public class MTDiagnoseAdapter
       extends org.cougaar.lib.quo.MTDiagnoseDelegate_client
       implements org.cougaar.lib.quo.DiagnoseQosket 
{
  private org.cougaar.lib.quo.DiagnoseQosketImpl qosket;

  // Constructor for BQAdapter
  public MTDiagnoseAdapter() 
  {
     this.qosket  = new org.cougaar.lib.quo.DiagnoseQosketImpl();
     set_qosket (qosket);
  }

  public void initSysconds (com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
     qosket.initSysconds(kernel); 
  }

  public void initCallbacks ()
  {
     qosket.initCallbacks(); 
  }

  public void linkContract (com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
     set_contract_Diagnose( qosket.initContract (kernel) );
  }

  public void linkRemoteObject( org.cougaar.core.mts.MT remote_obj)
  {
     set_remoteObj ( remote_obj );
  }

  // Qosket methods from IDL
  // inherited methods and attributes of org.cougaar.lib.quo.DiagnoseQosket
  public void setInstrumentedServer(java.lang.Object server)
  {
     qosket.setInstrumentedServer ( server );
  }


  // local methods and attributes of org.cougaar.lib.quo.DiagnoseQosket
}

