/* -*- JAVA -*- $Id: RemoteSSLQosketSkel.java,v 1.4 2001-11-06 13:52:12 psharma Exp $ */

// ****** Code generated by the QuO codegenerator version 3.0.7 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo ;

abstract public class RemoteSSLQosketSkel
         implements org.cougaar.lib.quo.RemoteSSLQosket, 
         org.cougaar.lib.quo.RemoteSSLDelegateQosket
{
  // Sysconds from contract arglist
  protected com.bbn.quo.rmi.ExpectedCapacitySC Bandwidth;
  protected com.bbn.quo.rmi.ValueSC UseSSL;
  protected com.bbn.quo.rmi.ValueSC trust;

  // Callbacks from contract arglist

  // Syscondseqs from contract arglist

  // Callbacks from contract arglist

  // Contract
  protected com.bbn.quo.rmi.Contract quo_RemoteSSL;

  // Qosket members

  // Subclass Responsibility to override this function 
  public void initSysconds  (com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
  }

  // Subclass Responsibility to override this function 
  public void initCallbacks ()
  { 
  } 

  public com.bbn.quo.rmi.Contract initContract(String name, com.bbn.quo.rmi.QuoKernel kernel)
  throws java.rmi.RemoteException 
  {
    com.bbn.quo.rmi.Contract result = null;
    if (name.equals ("RemoteSSL")) {
      com.bbn.quo.rmi.SysCond[] sysconds =  new com.bbn.quo.rmi.SysCond[3]; 
      sysconds[0] = Bandwidth;
      sysconds[1] = UseSSL;
      sysconds[2] = trust;

      com.bbn.quo.rmi.Callback[] callbacks =  new com.bbn.quo.rmi.Callback[0]; 

      quo_RemoteSSL = kernel.bindContract("RemoteSSL", "org::cougaar::lib::quo::RemoteSSL", sysconds , callbacks ); 
      result = quo_RemoteSSL;
    } else {
    } // else 
    return result;
  } // initContract

} // class

