/* -*- JAVA -*- $Id: RemoteSSLQosket.java,v 1.2 2001-11-02 17:07:56 psharma Exp $ */

// ****** Code generated by the QuO codegenerator version 3.0.7 ******
// QuO and the QuO codegenerator have been developed by 
// BBN Technologies.

// Information about QuO is available at:
// http://www.dist-systems.bbn.com/tech/QuO



package org.cougaar.lib.quo;

public interface RemoteSSLQosket
{
  public void setDestinationLink(org.cougaar.core.mts.DestinationLink link);
  public void setServices(org.cougaar.core.qos.monitor.ResourceMonitorService rms, org.cougaar.core.qos.monitor.QosMonitorService qms);
}
