package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/BadAttributeValueExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

public final class BadAttributeValueExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.BadAttributeValueException value = null;

  public BadAttributeValueExceptionHolder ()
  {
  }

  public BadAttributeValueExceptionHolder (org.cougaar.qos.ResourceStatus.BadAttributeValueException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.BadAttributeValueExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.BadAttributeValueExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.BadAttributeValueExceptionHelper.type ();
  }

}
