package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/CrossesThresholdQualifierFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the given threshold.
public interface CrossesThresholdQualifierFactoryOperations  extends org.cougaar.qos.ResourceStatus.QualifierFactoryOperations
{
  org.cougaar.qos.ResourceStatus.Qualifier getQualifier (double threshold);
} // interface CrossesThresholdQualifierFactoryOperations
