package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/CrossesThresholdQualifierFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// the given threshold.
public interface CrossesThresholdQualifierFactoryOperations  extends org.cougaar.qos.ResourceStatus.QualifierFactoryOperations
{
  org.cougaar.qos.ResourceStatus.Qualifier getQualifier (double threshold);
} // interface CrossesThresholdQualifierFactoryOperations
