package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/CrossesThresholdQualifierFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the given threshold.
public final class CrossesThresholdQualifierFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.CrossesThresholdQualifierFactory value = null;

  public CrossesThresholdQualifierFactoryHolder ()
  {
  }

  public CrossesThresholdQualifierFactoryHolder (org.cougaar.qos.ResourceStatus.CrossesThresholdQualifierFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.CrossesThresholdQualifierFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.CrossesThresholdQualifierFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.CrossesThresholdQualifierFactoryHelper.type ();
  }

}
