package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/DataValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

public final class DataValue implements org.omg.CORBA.portable.IDLEntity
{

  /**
    * 
    */
   private static final long serialVersionUID = 1L;

// when it entered the rss
  public long timestamp = 0;

  // how quickly its usefulness decreases
  public long halflife = 0;

  // how believable it is (0-1)
  public double credibility = 0;

  // what units it's in (not usually filled in)
  public String units = null;

  // where it came from
  public String provenance = null;

  // the raw value
  public org.cougaar.qos.ResourceStatus.data_value value = null;

  public DataValue ()
  {
  } // ctor

  public DataValue (long _timestamp, long _halflife, double _credibility, String _units, String _provenance, org.cougaar.qos.ResourceStatus.data_value _value)
  {
    timestamp = _timestamp;
    halflife = _halflife;
    credibility = _credibility;
    units = _units;
    provenance = _provenance;
    value = _value;
  } // ctor

} // class DataValue
