package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/data_typesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// a data_value (DataValue).
public final class data_typesHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.data_types value = null;

  public data_typesHolder ()
  {
  }

  public data_typesHolder (org.cougaar.qos.ResourceStatus.data_types initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.data_typesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.data_typesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.data_typesHelper.type ();
  }

}
