package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/data_types.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// a data_value (DataValue).
public class data_types implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static org.cougaar.qos.ResourceStatus.data_types[] __array = new org.cougaar.qos.ResourceStatus.data_types [__size];

  public static final int _number_data = 0;
  public static final org.cougaar.qos.ResourceStatus.data_types number_data = new org.cougaar.qos.ResourceStatus.data_types(_number_data);
  public static final int _string_data = 1;
  public static final org.cougaar.qos.ResourceStatus.data_types string_data = new org.cougaar.qos.ResourceStatus.data_types(_string_data);
  public static final int _boolean_data = 2;
  public static final org.cougaar.qos.ResourceStatus.data_types boolean_data = new org.cougaar.qos.ResourceStatus.data_types(_boolean_data);

  public int value ()
  {
    return __value;
  }

  public static org.cougaar.qos.ResourceStatus.data_types from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected data_types (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class data_types
