package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/EveryQualifierFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// the  set are satisfied
public interface EveryQualifierFactoryOperations  extends org.cougaar.qos.ResourceStatus.QualifierFactoryOperations
{
  org.cougaar.qos.ResourceStatus.Qualifier getQualifier (org.cougaar.qos.ResourceStatus.Qualifier[] qualifiers);
} // interface EveryQualifierFactoryOperations
