package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/EveryQualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set are satisfied
public interface EveryQualifierFactory extends EveryQualifierFactoryOperations, org.cougaar.qos.ResourceStatus.QualifierFactory 
{
} // interface EveryQualifierFactory
