package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/EveryQualifierFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set are satisfied
public final class EveryQualifierFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.EveryQualifierFactory value = null;

  public EveryQualifierFactoryHolder ()
  {
  }

  public EveryQualifierFactoryHolder (org.cougaar.qos.ResourceStatus.EveryQualifierFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.EveryQualifierFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.EveryQualifierFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.EveryQualifierFactoryHelper.type ();
  }

}
