package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/ExceedsThresholdQualifierFactoryPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// greater than the given threshold.
public class ExceedsThresholdQualifierFactoryPOATie extends ExceedsThresholdQualifierFactoryPOA
{

  // Constructors

  public ExceedsThresholdQualifierFactoryPOATie ( org.cougaar.qos.ResourceStatus.ExceedsThresholdQualifierFactoryOperations delegate ) {
      this._impl = delegate;
  }
  public ExceedsThresholdQualifierFactoryPOATie ( org.cougaar.qos.ResourceStatus.ExceedsThresholdQualifierFactoryOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.cougaar.qos.ResourceStatus.ExceedsThresholdQualifierFactoryOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.cougaar.qos.ResourceStatus.ExceedsThresholdQualifierFactoryOperations delegate ) {
      this._impl = delegate;
  }
  @Override
public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public org.cougaar.qos.ResourceStatus.Qualifier getQualifier (double threshold)
  {
    return _impl.getQualifier(threshold);
  } // getQualifier

  private org.cougaar.qos.ResourceStatus.ExceedsThresholdQualifierFactoryOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ExceedsThresholdQualifierFactoryPOATie
