package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/MinDeltaQualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// numeric values.
public interface MinDeltaQualifierFactory extends MinDeltaQualifierFactoryOperations, org.cougaar.qos.ResourceStatus.QualifierFactory, org.omg.CORBA.portable.IDLEntity 
{
} // interface MinDeltaQualifierFactory
