package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/MinDeltaQualifierFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// numeric values.
public final class MinDeltaQualifierFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.MinDeltaQualifierFactory value = null;

  public MinDeltaQualifierFactoryHolder ()
  {
  }

  public MinDeltaQualifierFactoryHolder (org.cougaar.qos.ResourceStatus.MinDeltaQualifierFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.MinDeltaQualifierFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.MinDeltaQualifierFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.MinDeltaQualifierFactoryHelper.type ();
  }

}
