package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/MinDeltaQualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// numeric values.
public interface MinDeltaQualifierFactory extends MinDeltaQualifierFactoryOperations, org.cougaar.qos.ResourceStatus.QualifierFactory 
{
} // interface MinDeltaQualifierFactory
