package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/NoSuchAttributeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

public final class NoSuchAttributeException extends org.omg.CORBA.UserException
{
  public String attribute_name = null;

  public NoSuchAttributeException ()
  {
    super(NoSuchAttributeExceptionHelper.id());
  } // ctor

  public NoSuchAttributeException (String _attribute_name)
  {
    super(NoSuchAttributeExceptionHelper.id());
    attribute_name = _attribute_name;
  } // ctor


  public NoSuchAttributeException (String $reason, String _attribute_name)
  {
    super(NoSuchAttributeExceptionHelper.id() + "  " + $reason);
    attribute_name = _attribute_name;
  } // ctor

} // class NoSuchAttributeException
