package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/NoSuchAttributeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

public final class NoSuchAttributeException extends org.omg.CORBA.UserException
{
  /**
    * 
    */
   private static final long serialVersionUID = 1L;
public String attribute_name = null;

  public NoSuchAttributeException ()
  {
    super(NoSuchAttributeExceptionHelper.id());
  } // ctor

  public NoSuchAttributeException (String _attribute_name)
  {
    super(NoSuchAttributeExceptionHelper.id());
    attribute_name = _attribute_name;
  } // ctor


  public NoSuchAttributeException (String $reason, String _attribute_name)
  {
    super(NoSuchAttributeExceptionHelper.id() + "  " + $reason);
    attribute_name = _attribute_name;
  } // ctor

} // class NoSuchAttributeException
