package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/ParameterListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// sorts of values.
public final class ParameterListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ParameterListHolder ()
  {
  }

  public ParameterListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.ParameterListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.ParameterListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.ParameterListHelper.type ();
  }

}
