package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/QualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// simple.
public interface QualifierFactory extends QualifierFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface QualifierFactory
