package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/QualifierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

public interface QualifierOperations 
{
  void getAttribute (String attribute_name, org.cougaar.qos.ResourceStatus.data_valueHolder attribute_value) throws org.cougaar.qos.ResourceStatus.NoSuchAttributeException, org.cougaar.qos.ResourceStatus.BadAttributeValueException;
  void setAttribute (String attribute_name, org.cougaar.qos.ResourceStatus.data_value attrobute_value) throws org.cougaar.qos.ResourceStatus.NoSuchAttributeException, org.cougaar.qos.ResourceStatus.BadAttributeValueException;
} // interface QualifierOperations
