package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/QualifierSetHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

abstract public class QualifierSetHelper
{
  private static String  _id = "IDL:org/cougaar/qos/ResourceStatus/QualifierSet:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cougaar.qos.ResourceStatus.Qualifier[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cougaar.qos.ResourceStatus.Qualifier[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.cougaar.qos.ResourceStatus.QualifierHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.cougaar.qos.ResourceStatus.QualifierSetHelper.id (), "QualifierSet", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cougaar.qos.ResourceStatus.Qualifier[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cougaar.qos.ResourceStatus.Qualifier value[] = null;
    int _len0 = istream.read_long ();
    value = new org.cougaar.qos.ResourceStatus.Qualifier[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.cougaar.qos.ResourceStatus.QualifierHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cougaar.qos.ResourceStatus.Qualifier[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.cougaar.qos.ResourceStatus.QualifierHelper.write (ostream, value[_i0]);
  }

}
