package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/Qualifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

public interface Qualifier extends QualifierOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Qualifier
