package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/QualifierPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

public class QualifierPOATie extends QualifierPOA
{

  // Constructors

  public QualifierPOATie ( org.cougaar.qos.ResourceStatus.QualifierOperations delegate ) {
      this._impl = delegate;
  }
  public QualifierPOATie ( org.cougaar.qos.ResourceStatus.QualifierOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.cougaar.qos.ResourceStatus.QualifierOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.cougaar.qos.ResourceStatus.QualifierOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void getAttribute (String attribute_name, org.cougaar.qos.ResourceStatus.data_valueHolder attribute_value) throws org.cougaar.qos.ResourceStatus.NoSuchAttributeException, org.cougaar.qos.ResourceStatus.BadAttributeValueException
  {
    _impl.getAttribute(attribute_name, attribute_value);
  } // getAttribute

  public void setAttribute (String attribute_name, org.cougaar.qos.ResourceStatus.data_value attrobute_value) throws org.cougaar.qos.ResourceStatus.NoSuchAttributeException, org.cougaar.qos.ResourceStatus.BadAttributeValueException
  {
    _impl.setAttribute(attribute_name, attrobute_value);
  } // setAttribute

  private org.cougaar.qos.ResourceStatus.QualifierOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class QualifierPOATie
