package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/ResourceNode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/

public final class ResourceNode implements org.omg.CORBA.portable.IDLEntity
{
  public String kind = null;
  public String parameters[] = null;

  public ResourceNode ()
  {
  } // ctor

  public ResourceNode (String _kind, String[] _parameters)
  {
    kind = _kind;
    parameters = _parameters;
  } // ctor

} // class ResourceNode
