package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/ResourceNodeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

abstract public class ResourceNodeHelper
{
  private static String  _id = "IDL:com/bbn/ResourceStatus/ResourceNode/ResourceNode:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cougaar.qos.ResourceStatus.ResourceNode that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cougaar.qos.ResourceStatus.ResourceNode extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "kind",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cougaar.qos.ResourceStatus.ParameterListHelper.id (), "ParameterList", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "parameters",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cougaar.qos.ResourceStatus.ResourceNodeHelper.id (), "ResourceNode", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cougaar.qos.ResourceStatus.ResourceNode read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cougaar.qos.ResourceStatus.ResourceNode value = new org.cougaar.qos.ResourceStatus.ResourceNode ();
    value.kind = istream.read_string ();
    value.parameters = org.cougaar.qos.ResourceStatus.ParameterListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cougaar.qos.ResourceStatus.ResourceNode value)
  {
    ostream.write_string (value.kind);
    org.cougaar.qos.ResourceStatus.ParameterListHelper.write (ostream, value.parameters);
  }

}
