package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/ResourceNodeSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// Likewise RSSSeq.
public final class ResourceNodeSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.ResourceNode value[] = null;

  public ResourceNodeSeqHolder ()
  {
  }

  public ResourceNodeSeqHolder (org.cougaar.qos.ResourceStatus.ResourceNode[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.ResourceNodeSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.ResourceNodeSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.ResourceNodeSeqHelper.type ();
  }

}
