package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/ResourceStatusServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// syntactic problem with the argument.
public interface ResourceStatusServiceOperations 
{

  // This call is non-blocking by design.
  boolean query (org.cougaar.qos.ResourceStatus.ResourceNode[] formula, org.cougaar.qos.ResourceStatus.DataValueHolder result);
  boolean query_s (String formula, org.cougaar.qos.ResourceStatus.DataValueHolder result) throws org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // an exception in the former case.
  boolean blockingQuery (org.cougaar.qos.ResourceStatus.ResourceNode[] formula, long timeout, org.cougaar.qos.ResourceStatus.DataValueHolder result);
  boolean blockingQuery_s (String formula, long timeout, org.cougaar.qos.ResourceStatus.DataValueHolder result) throws org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // one corresponds to a given callback invocation.
  boolean unqualifiedSubscribe (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, org.cougaar.qos.ResourceStatus.ResourceNode[] formula, int callback_id);
  boolean unqualifiedSubscribe_s (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, String formula, int callback_id) throws org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // qualifier.
  boolean qualifiedSubscribe (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, org.cougaar.qos.ResourceStatus.ResourceNode[] formula, int callback_id, org.cougaar.qos.ResourceStatus.Qualifier qualifier_);
  boolean qualifiedSubscribe_s (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, String formula, int callback_id, org.cougaar.qos.ResourceStatus.Qualifier qualifier_) throws org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // given listener.
  void unsubscribe (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, org.cougaar.qos.ResourceStatus.ResourceNode[] formula);
  void unsubscribe_s (org.cougaar.qos.ResourceStatus.RSSSubscriber listener, String formula) throws org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // request a Qualifier.
  org.cougaar.qos.ResourceStatus.QualifierFactory getQualifierFactory (org.cougaar.qos.ResourceStatus.QualifierKind kind);

  // context rather than a formula.
  boolean invoke (org.cougaar.qos.ResourceStatus.ResourceNode[] resource_context, String method_name, String[] args) throws org.cougaar.qos.ResourceStatus.NoSuchMethodException;
  boolean invoke_s (String resource_context, String method_name, String[] args) throws org.cougaar.qos.ResourceStatus.NoSuchMethodException, org.cougaar.qos.ResourceStatus.ResourceDescriptionParseException;

  // raw value.
  void pushString (String key, String raw_value);
  void pushLong (String key, int raw_value);

  // soon go away.
  void addDependency (org.cougaar.qos.ResourceStatus.ResourceNode resource, org.cougaar.qos.ResourceStatus.ResourceNode[] node_dependencies, org.cougaar.qos.ResourceStatus.ResourceStatusService[] rss_dependencies);
} // interface ResourceStatusServiceOperations
