package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/ResourceDescriptionParseException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

public final class ResourceDescriptionParseException extends org.omg.CORBA.UserException
{
  public String description = null;
  public String reason = null;

  public ResourceDescriptionParseException ()
  {
    super(ResourceDescriptionParseExceptionHelper.id());
  } // ctor

  public ResourceDescriptionParseException (String _description, String _reason)
  {
    super(ResourceDescriptionParseExceptionHelper.id());
    description = _description;
    reason = _reason;
  } // ctor


  public ResourceDescriptionParseException (String $reason, String _description, String _reason)
  {
    super(ResourceDescriptionParseExceptionHelper.id() + "  " + $reason);
    description = _description;
    reason = _reason;
  } // ctor

} // class ResourceDescriptionParseException
