package org.cougaar.qos.ResourceStatus;

/**
* com/bbn/ResourceStatus/RSSSubscriberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// to the RSS should implement this.
public final class RSSSubscriberHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.RSSSubscriber value = null;

  public RSSSubscriberHolder ()
  {
  }

  public RSSSubscriberHolder (org.cougaar.qos.ResourceStatus.RSSSubscriber initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.RSSSubscriberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.RSSSubscriberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.RSSSubscriberHelper.type ();
  }

}
