package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/RSSSubscriberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// to the RSS should implement this.
public interface RSSSubscriberOperations 
{
  void dataUpdate (int callback_id, org.cougaar.qos.ResourceStatus.DataValue value);
} // interface RSSSubscriberOperations
