package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/RSSSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/

abstract public class RSSSeqHelper
{
  private static String  _id = "IDL:com/bbn/ResourceStatus/RSSSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cougaar.qos.ResourceStatus.ResourceStatusService[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cougaar.qos.ResourceStatus.ResourceStatusService[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.cougaar.qos.ResourceStatus.ResourceStatusServiceHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.cougaar.qos.ResourceStatus.RSSSeqHelper.id (), "RSSSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cougaar.qos.ResourceStatus.ResourceStatusService[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cougaar.qos.ResourceStatus.ResourceStatusService value[] = null;
    int _len0 = istream.read_long ();
    value = new org.cougaar.qos.ResourceStatus.ResourceStatusService[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.cougaar.qos.ResourceStatus.ResourceStatusServiceHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cougaar.qos.ResourceStatus.ResourceStatusService[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.cougaar.qos.ResourceStatus.ResourceStatusServiceHelper.write (ostream, value[_i0]);
  }

}
