package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/RSSSubscriberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// to the RSS should implement this.
public interface RSSSubscriberOperations 
{
  void dataUpdate (int callback_id, org.cougaar.qos.ResourceStatus.DataValue value);
} // interface RSSSubscriberOperations
