package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/SomeQualifierFactoryPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set is satisfied
public class SomeQualifierFactoryPOATie extends SomeQualifierFactoryPOA
{

  // Constructors

  public SomeQualifierFactoryPOATie ( org.cougaar.qos.ResourceStatus.SomeQualifierFactoryOperations delegate ) {
      this._impl = delegate;
  }
  public SomeQualifierFactoryPOATie ( org.cougaar.qos.ResourceStatus.SomeQualifierFactoryOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.cougaar.qos.ResourceStatus.SomeQualifierFactoryOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.cougaar.qos.ResourceStatus.SomeQualifierFactoryOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public org.cougaar.qos.ResourceStatus.Qualifier getQualifier (org.cougaar.qos.ResourceStatus.Qualifier[] qualifiers)
  {
    return _impl.getQualifier(qualifiers);
  } // getQualifier

  private org.cougaar.qos.ResourceStatus.SomeQualifierFactoryOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SomeQualifierFactoryPOATie
