package org.cougaar.qos.ResourceStatus;

/**
* org/cougaar/qos/ResourceStatus/SomeQualifierFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set is satisfied
public final class SomeQualifierFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cougaar.qos.ResourceStatus.SomeQualifierFactory value = null;

  public SomeQualifierFactoryHolder ()
  {
  }

  public SomeQualifierFactoryHolder (org.cougaar.qos.ResourceStatus.SomeQualifierFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cougaar.qos.ResourceStatus.SomeQualifierFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cougaar.qos.ResourceStatus.SomeQualifierFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cougaar.qos.ResourceStatus.SomeQualifierFactoryHelper.type ();
  }

}
