package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/SomeQualifierFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set is satisfied
public interface SomeQualifierFactoryOperations  extends org.cougaar.qos.ResourceStatus.QualifierFactoryOperations
{
  org.cougaar.qos.ResourceStatus.Qualifier getQualifier (org.cougaar.qos.ResourceStatus.Qualifier[] qualifiers);
} // interface SomeQualifierFactoryOperations
