package org.cougaar.qos.ResourceStatus;


/**
* org/cougaar/qos/ResourceStatus/SomeQualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from qrs.idl
* Tuesday, August 7, 2007 11:57:30 AM EDT
*/


// the  set is satisfied
public interface SomeQualifierFactory extends SomeQualifierFactoryOperations, org.cougaar.qos.ResourceStatus.QualifierFactory, org.omg.CORBA.portable.IDLEntity 
{
} // interface SomeQualifierFactory
