package org.cougaar.qos.ResourceStatus;


/**
* com/bbn/ResourceStatus/SomeQualifierFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Volumes/Data/Projects/quo/idl/rss.idl
* Monday, August 6, 2007 12:12:54 PM EDT
*/


// the  set is satisfied
public interface SomeQualifierFactory extends SomeQualifierFactoryOperations, org.cougaar.qos.ResourceStatus.QualifierFactory, org.omg.CORBA.portable.IDLEntity 
{
} // interface SomeQualifierFactory
